#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
本地 .db (SQLite) -> MariaDB/MySQL 兼容 .sql 转储（纯离线，无需联网）
读取原始 SQLite 库，按 MySQL 方言重新生成建表+数据，可直接 source 进 MariaDB。

用法:
  python db_to_mariadb.py <输入.db> <输出.sql>
"""
import sys
import os
import sqlite3


def map_type(decl):
    d = (decl or "").upper()
    if "BIGINT" in d:
        return "BIGINT"
    if "INT" in d:          # integer / int / smallint ...
        return "INT"
    if "DOUB" in d or "REAL" in d or "FLOA" in d:
        return "DOUBLE"
    if "BOOL" in d:
        return "TINYINT"
    if "BLOB" in d:
        return "BLOB"
    if "CHAR" in d or "TEXT" in d or "CLOB" in d:
        return "TEXT"
    if "DATE" in d or "TIME" in d:
        return "DATETIME"
    return "TEXT"


def qident(name):
    return "`" + name.replace("`", "``") + "`"


def esc(v):
    # MySQL 单引号串内用 '' 转义单引号；反斜杠按转义符处理，先翻倍
    return v.replace("\\", "\\\\").replace("'", "''")


def convert(db_path, out_path):
    if not os.path.isfile(db_path):
        raise FileNotFoundError(f"找不到文件: {db_path}")

    conn = sqlite3.connect(db_path)
    conn.text_factory = str
    cur = conn.cursor()
    cur.execute(
        "SELECT name FROM sqlite_master WHERE type='table' "
        "AND name NOT LIKE 'sqlite_%' ORDER BY name"
    )
    tables = [r[0] for r in cur.fetchall()]

    out = []
    out.append(f"-- MariaDB/MySQL dump from {os.path.basename(db_path)}")
    out.append("-- generated by db_to_mariadb.py (SQLite -> MariaDB)")
    out.append("SET NAMES utf8mb4;")
    out.append("SET FOREIGN_KEY_CHECKS=0;")
    out.append("")

    for t in tables:
        cur.execute(f"PRAGMA table_info('{t}')")
        cols = cur.fetchall()  # cid,name,type,notnull,dflt_value,pk
        pk_cols = [c[1] for c in cols if c[5]]

        col_defs = []
        for cid, cname, ctype, notnull, dflt, pk in cols:
            if len(pk_cols) == 1 and cname == pk_cols[0] and "INT" in (ctype or "").upper():
                col_defs.append(qident(cname) + " " + map_type(ctype) + " AUTO_INCREMENT PRIMARY KEY")
                continue
            cdef = qident(cname) + " " + map_type(ctype)
            if notnull:
                cdef += " NOT NULL"
            col_defs.append(cdef)

        out.append(f"DROP TABLE IF EXISTS {qident(t)};")
        create = f"CREATE TABLE {qident(t)} (\n  " + ",\n  ".join(col_defs)
        if len(pk_cols) > 1:
            create += ",\n  PRIMARY KEY (" + ", ".join(qident(c) for c in pk_cols) + ")"
        create += "\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;"
        out.append(create)
        out.append("")

        # 数据（分块多值 INSERT，降低语句数）
        cur.execute(f"SELECT * FROM {qident(t)}")
        rows = cur.fetchall()
        if not rows:
            continue
        col_names = [c[1] for c in cols]
        col_list = ", ".join(qident(c) for c in col_names)
        chunk = 500
        for i in range(0, len(rows), chunk):
            batch = rows[i:i + chunk]
            val_strs = []
            for row in batch:
                vals = []
                for v in row:
                    if v is None:
                        vals.append("NULL")
                    elif isinstance(v, (bytes, bytearray)):
                        vals.append("X'" + v.hex() + "'")
                    elif isinstance(v, bool):
                        vals.append("1" if v else "0")
                    elif isinstance(v, int):
                        vals.append(str(v))
                    elif isinstance(v, float):
                        vals.append(str(v))
                    else:
                        vals.append("'" + esc(str(v)) + "'")
                val_strs.append("(" + ",".join(vals) + ")")
            out.append(f"INSERT INTO {qident(t)} ({col_list}) VALUES " + ", ".join(val_strs) + ";")

    out.append("SET FOREIGN_KEY_CHECKS=1;")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")
    conn.close()

    return f"已生成: {out_path}  ({os.path.getsize(out_path):,} 字节, {len(tables)} 张表)"


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("用法: python db_to_mariadb.py <输入.db> <输出.sql>")
        sys.exit(1)
    try:
        print(convert(sys.argv[1], sys.argv[2]))
    except Exception as e:
        print(f"[错误] {e}")
        sys.exit(1)
